### ISSUE TITLE
NPE on start

### ISSUE THREAD

**Issue by agilob** [basil2style/getid#2]
I think it's because I don't have Gapps on my device. 

```
03-21 23:52:11.410 D/org.fdroid.fdroid.AppDetails(2702): Getting application details for makeinfo.com.getid
03-21 23:52:12.641 D/org.fdroid.fdroid.net.ApkDownloader(2702): Downloading apk from https://f-droid.org/repo/makeinfo.com.getid_1.apk
03-21 23:52:12.651 I/org.fdroid.fdroid.net.HttpDownloader(2702): Downloading from https://f-droid.org/repo/makeinfo.com.getid_1.apk
03-21 23:52:13.682 D/FDroid  (2702): Using cached apk at /data/data/org.fdroid.fdroid/cache/apks/makeinfo.com.getid_1.apk
03-21 23:52:13.682 D/FDroid  (2702): Download finished: /data/data/org.fdroid.fdroid/cache/apks/makeinfo.com.getid_1.apk
03-21 23:52:13.892 W/ActivityManager(2085): No content provider found for permission revoke: file:///data/data/org.fdroid.fdroid/cache/apks/makeinfo.com.getid_1.apk
03-21 23:52:13.932 W/ActivityManager(2085): No content provider found for permission revoke: file:///data/data/org.fdroid.fdroid/cache/apks/makeinfo.com.getid_1.apk
03-21 23:52:14.603 I/PackageManager(2085): Running dexopt on: makeinfo.com.getid
03-21 23:52:16.085 I/ActivityManager(2085): Force stopping makeinfo.com.getid appid=10061 user=-1: update pkg
03-21 23:52:16.265 W/PackageManager(2085): Unknown permission com.google.android.providers.gsf.permission.READ_GSERVICES in package makeinfo.com.getid
03-21 23:52:16.695 D/BackupManagerService(2085): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:makeinfo.com.getid flg=0x4000010 (has extras) }
03-21 23:52:16.735 D/Launcher.Model(2522): shortcutWasRestored is false for makeinfo.com.getid/makeinfo.com.getid.MainActivity
03-21 23:52:17.236 D/FDroid  (2702): Installer package name for makeinfo.com.getid set successfully
03-21 23:52:17.236 D/org.fdroid.fdroid.AppDetails(2702): Getting application details for makeinfo.com.getid
03-21 23:52:20.259 D/FDroid  (2702): PackageReceiver received [action = 'android.intent.action.PACKAGE_ADDED', data = 'package:makeinfo.com.getid']
03-21 23:52:20.289 D/FDroid  (2702): Inserting installed app info for 'makeinfo.com.getid' (v1)
03-21 23:52:20.429 D/org.fdroid.fdroid.AppDetails(2702): Getting application details for makeinfo.com.getid
03-21 23:52:21.450 I/Timeline(2702): Timeline: Activity_launch_request id:makeinfo.com.getid time:3740931
03-21 23:52:21.450 I/ActivityManager(2085): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=makeinfo.com.getid cmp=makeinfo.com.getid/.MainActivity} from pid 2702
03-21 23:52:21.570 I/ActivityManager(2085): Start proc makeinfo.com.getid for activity makeinfo.com.getid/.MainActivity: pid=14412 uid=10061 gids={50061}
03-21 23:52:21.680 D/ActivityThread(14412): handleBindApplication:makeinfo.com.getid
03-21 23:52:22.080 E/AndroidRuntime(14412): Process: makeinfo.com.getid, PID: 14412
03-21 23:52:22.080 E/AndroidRuntime(14412): java.lang.RuntimeException: Unable to start activity ComponentInfo{makeinfo.com.getid/makeinfo.com.getid.MainActivity}: java.lang.NullPointerException
03-21 23:52:22.080 E/AndroidRuntime(14412):     at makeinfo.com.getid.MainActivity.getGsfAndroidId(MainActivity.java:239)
03-21 23:52:22.080 E/AndroidRuntime(14412):     at makeinfo.com.getid.MainActivity.onCreate(MainActivity.java:60)
03-21 23:52:22.180 W/ActivityManager(2085):   Force finishing activity makeinfo.com.getid/.MainActivity
03-21 23:52:22.751 W/ActivityManager(2085): Activity pause timeout for ActivityRecord{423a4e58 u0 makeinfo.com.getid/.MainActivity t8 f}
03-21 23:52:24.523 I/ActivityManager(2085): Process makeinfo.com.getid (pid 14412) has died.
03-21 23:52:26.154 D/org.fdroid.fdroid.AppDetails(2702): Getting application details for makeinfo.com.getid
03-21 23:52:28.447 I/Timeline(2702): Timeline: Activity_launch_request id:makeinfo.com.getid time:3747937
03-21 23:52:28.447 I/ActivityManager(2085): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=makeinfo.com.getid cmp=makeinfo.com.getid/.MainActivity} from pid 2702
03-21 23:52:28.637 I/ActivityManager(2085): Start proc makeinfo.com.getid for activity makeinfo.com.getid/.MainActivity: pid=14438 uid=10061 gids={50061}
03-21 23:52:28.717 D/ActivityThread(14438): handleBindApplication:makeinfo.com.getid
03-21 23:52:29.067 E/AndroidRuntime(14438): Process: makeinfo.com.getid, PID: 14438
03-21 23:52:29.067 E/AndroidRuntime(14438): java.lang.RuntimeException: Unable to start activity ComponentInfo{makeinfo.com.getid/makeinfo.com.getid.MainActivity}: java.lang.NullPointerException
03-21 23:52:29.067 E/AndroidRuntime(14438):     at makeinfo.com.getid.MainActivity.getGsfAndroidId(MainActivity.java:239)
03-21 23:52:29.067 E/AndroidRuntime(14438):     at makeinfo.com.getid.MainActivity.onCreate(MainActivity.java:60)
03-21 23:52:29.117 W/ActivityManager(2085):   Force finishing activity makeinfo.com.getid/.MainActivity
03-21 23:52:29.738 W/ActivityManager(2085): Activity pause timeout for ActivityRecord{41d963c0 u0 makeinfo.com.getid/.MainActivity t9 f}
03-21 23:52:32.430 I/ActivityManager(2085): Process makeinfo.com.getid (pid 14438) has died.
03-21 23:52:57.975 I/Timeline(2522): Timeline: Activity_launch_request id:makeinfo.com.getid time:3777467
03-21 23:52:57.975 I/ActivityManager(2085): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=makeinfo.com.getid/.MainActivity} from pid 2522
03-21 23:52:58.206 I/ActivityManager(2085): Start proc makeinfo.com.getid for activity makeinfo.com.getid/.MainActivity: pid=14594 uid=10061 gids={50061}
03-21 23:52:58.276 D/ActivityThread(14594): handleBindApplication:makeinfo.com.getid
03-21 23:52:58.636 E/AndroidRuntime(14594): Process: makeinfo.com.getid, PID: 14594
03-21 23:52:58.636 E/AndroidRuntime(14594): java.lang.RuntimeException: Unable to start activity ComponentInfo{makeinfo.com.getid/makeinfo.com.getid.MainActivity}: java.lang.NullPointerException
03-21 23:52:58.636 E/AndroidRuntime(14594):     at makeinfo.com.getid.MainActivity.getGsfAndroidId(MainActivity.java:239)
03-21 23:52:58.636 E/AndroidRuntime(14594):     at makeinfo.com.getid.MainActivity.onCreate(MainActivity.java:60)
03-21 23:52:58.636 W/ActivityManager(2085):   Force finishing activity makeinfo.com.getid/.MainActivity
03-21 23:52:58.946 I/WindowManager(2085): Screenshot max retries 4 of Token{41f66ad8 ActivityRecord{41ec40e8 u0 makeinfo.com.getid/.MainActivity t11 f}} appWin=Window{42343d20 u0 Starting makeinfo.com.getid} drawState=4
03-21 23:52:59.457 W/ActivityManager(2085): Activity pause timeout for ActivityRecord{41ec40e8 u0 makeinfo.com.getid/.MainActivity t11 f}
03-21 23:53:00.330 I/ActivityManager(2085): Process makeinfo.com.getid (pid 14594) has died.
```

**Comment by basil2style** [comment]
Ya,its because of the Play Service.It check for gservices and getting null value..
